sigma67/ytmusicapi

.flake8
.pre-commit-config.yaml
.style.yapf
tests/test.py
ytmusicapi/helpers.py
ytmusicapi/parsers.py
ytmusicapi/setup.py
ytmusicapi/ytmusic.py

Now the following checks have to be passed before committing:
**YAPF hook check:**
Formats the staged files. If staged version differs from the correctly formatted version, the file is formatted correctly and the changes become unstaged, so the developer could review them.
**Flake8 hook check:**
Lints the staged files. If staged file had linting errors, pre-commit yields those errors and the changes become unstaged, so the developer could fix them.
If both checks were passed, commit is made.
Checks can be made explicitly with ``pre-commit run``.
I set up YAPF and Flake8, so that the code looked good enough, mostly. Also, I adjusted the  settings a little, so that the code in its current state passed the checks. Though almost all of Flake8 ignore settings are considered sane defaults, …

Implement pre-commit hooks

---

ytmusicapi/ytmusic.py

Fix empty description in get_playlist()

---

ytmusicapi/mixins/browsing.py
ytmusicapi/parsers.py

This PR fixes get_artist_albums if some albums don't have publication year. For example for https://music.youtube.com/channel/UCfUu_pLg6Uw-x_ntBWZmlwA

Fix for albums without publication year

---

ytmusicapi/mixins/browsing.py
ytmusicapi/parsers.py

This pull request fixes two "incomplete data" issues, each in separate commit. First is about artist, which don't have thumbnail, for example https://music.youtube.com/channel/UCDAPd3S5CBIEKXn-tvy57Lg (it doesn't have albums too, but still available in search). Second related to album without publication year, this time on artist page (https://music.youtube.com/channel/UCLZ7tlKC06ResyDmEStSrOw).

Fix exception when there is no thumbnail and album publication year on artist page

---

ytmusicapi/mixins/browsing.py

Some albums like following give no first track at the moment (rather start index from 2 instead of 1).
- [NCS: Infinity](https://music.youtube.com/browse/MPREb_cIll1xTklJL)
- [NCS: Alpha](https://music.youtube.com/browse/MPREb_PAcC7ycC6GP)
**Simply changing the index in this [line](https://github.com/sigma67/ytmusicapi/blob/d9c88009d8cfa849004f96d20e58495c06677436/ytmusicapi/mixins/browsing.py#L421) from 4 to 3 fixes the issue.**
With the following script:
```python
from ytmusicapi import YTMusic
from json import dumps
ytMusic = YTMusic()
print(dumps(ytMusic.get_album('MPREb_cIll1xTklJL')['tracks'], indent=4))
```
**Output before this change:**
<details>
```json
[
{
"index": "2",
"title": "Safari Fruits",
"thumbnails": [
{
"url": …
```

Fixes the issue #75

---

ytmusicapi/parsers/utils.py

This is a potential fix for #87.

Fix KeyError in get_continuations()

---

docs/source/usage.rst

Changing brand id to string. Now it works. 🥇

Update usage.rst - Brand Account-Support

---

tests/test.py
ytmusicapi/mixins/playlists.py

For this enhancement: https://github.com/sigma67/ytmusicapi/issues/176

After adding songs to a playlist: return the new setVideoId for each song

---

tests/test.py
ytmusicapi/mixins/browsing.py

Didn't really know where to put them, so I just shoved 'em into the browsing mixin...
...and I just now noticed @KoljaWindeler's comment about submitting the PR on #196... 🤦‍♂️

Added get_signatureTimestamp() and get_basejs_url() methods for #196.

---

tests/test.py
ytmusicapi/mixins/browsing.py
ytmusicapi/parsers/__init__.py

- added `get_mood_categories()` to retrieve the "Moods & Genres" categories and sub-categories from YTMusic
- added `get_mood_playlists()` to retrieve a list of playlists from a "Moods & Genres" category

Methods for browsing "moods and genres" playlists for #205

---

docs/source/reference.rst
tests/test.py
ytmusicapi/mixins/browsing.py
ytmusicapi/navigation.py
ytmusicapi/parsers/browsing.py

#32 
Added ability add favorite artists to https://music.youtube.com/tasteprofile. Implementation was based on the discussion in above issue

Added favorite artists to taste

---

tests/test.py
ytmusicapi/mixins/library.py
ytmusicapi/navigation.py
ytmusicapi/parsers/library.py

This is the pull request related to Issue #303.

Add playlistId key to the album dicts in parse_album

---

ytmusicapi/helpers.py

Fix KeyError when playlist is empty

---

ytmusicapi/locales/nl/LC_MESSAGES/base.po

Added Dutch translation

---

tests/test.py
ytmusicapi/mixins/search.py

Fix for KeyError when searching community_playlists or featured_playlists.
Also applies a small lint to tests.py.

Fix for KeyError when searching community_playlists or featured_playlists. Closes #420

---

ytmusicapi/navigation.py
ytmusicapi/parsers/browsing.py

I handled 'KeyError', and added new Navigation PATH in that case.

fixed KeyError in get_charts

---

ytmusicapi/mixins/browsing.py

This doesn't touch singles at all, as I'm frankly too dumb to figure that out
Fixes #439

Fix the currently present problem of `get_artist_albums` not working

---

.pre-commit-config.yaml

Adding the additional dependencies did indeed fix the errors. ty

pre-commit: add mypy additional_dependencies to fix stubs

---

.github/workflows/coverage.yml
.gitignore
tests/mixins/test_browsing.py
tests/mixins/test_explore.py
tests/mixins/test_library.py
tests/mixins/test_playlists.py
tests/mixins/test_search.py
tests/setup/setup_account.py
tests/test.example.cfg
ytmusicapi/mixins/_protocol.py
ytmusicapi/mixins/browsing.py
ytmusicapi/mixins/explore.py
ytmusicapi/parsers/explore.py
ytmusicapi/parsers/playlists.py
ytmusicapi/parsers/podcasts.py

This reverts commit b2113db0e15cbc9bec2e1c308bf4c144fb48a937.

Revert "get_playlist: fix albums on tracks" (#548)

---

README.rst
docs/source/reference.rst
tests/mixins/test_podcasts.py
ytmusicapi/mixins/playlists.py
ytmusicapi/mixins/podcasts.py
ytmusicapi/parsers/playlists.py
ytmusicapi/parsers/podcasts.py

get_episodes_playlist

---

ytmusicapi/parsers/_utils.py

make parse_menu_playlists more error proof

---

ytmusicapi/helpers.py

fix sum_total_duration failing if duration_seconds is not an int

---

ytmusicapi/mixins/playlists.py

re-add thumbnails to get_playlist

---

tests/mixins/test_search.py
ytmusicapi/parsers/i18n.py
ytmusicapi/parsers/search.py

search: fix missing artists when filtering songs/videos

---

ytmusicapi/mixins/library.py

Move songlist parsing get_history

---

tests/mixins/test_podcasts.py
ytmusicapi/parsers/podcasts.py

feat: #670 get_podcast get_episode thumbnails

---

tests/mixins/test_browsing.py
ytmusicapi/mixins/browsing.py

fix #713: get_artist radioId and shuffleId missing

---

docs/source/usage.rst
tests/auth/test_oauth.py
tests/test_ytmusic.py
ytmusicapi/auth/auth_parse.py
ytmusicapi/auth/types.py
ytmusicapi/ytmusic.py

- improved OAuth documentation, raise when oauth_credentials are missing
- removed option to disable session usage
- removed non-functional OAUTH_DEFAULT AuthType
- improved readability of ytmusic.py/YTMusicBase

refactor YTMusicBase, improve oauth doc

---

docs/Makefile

Make needs tabs, not spaces
Fixes https://github.com/sigma67/ytmusicapi/issues/733

Fix docs build

---

ytmusicapi/parsers/albums.py

fix #743: get_album() now returns None for 'audioPlaylistId'

---

ytmusicapi/parsers/search.py

add fallback for #799

---

tests/mixins/test_browsing.py
ytmusicapi/parsers/browsing.py

Handle channel links in `parse_mixed_content`:
```diff
[
{
"title": "Channels you may like",
"contents": [
-     None
+     {
+       "title": "MTV UK",
+       "browseId": "UCuwUfM8E79h2sqp34Fut6kw",
+       "subscribers": "2.32M",
+       "thumbnails": [...]
+     }
```

get_home: parse recommended channels
