sigma67/ytmusicapi

ytmusicapi/parsers.py, ytmusicapi/ytmusic.py
Collaborative playlists allow collaborators to remove items, so the items have `setVideoId` assigned, but the playlists themselves do not appear editable - they are not owned.
Make it so that attempt to obtain `setVideoId` is performed also in such cases.
Fixes #23.
=> Always try to obtain setVideoId of playlist items

ytmusicapi/mixins/browsing.py, ytmusicapi/parsers.py
Some artists doesn't have like buttons for songs list, for example https://music.youtube.com/channel/UC4HYnYJf1UxodkVFQkUHF9A. Because of this, get_artist() returns empty song list, and pollutes stdout with messages
```
Item 2: 'topLevelButtons'
Item 3: 'topLevelButtons'
Item 4: 'topLevelButtons'
Item 5: 'topLevelButtons'
Item 6: 'topLevelButtons'
```
This PR fixes it. It depends on previous PR.
=> Fix for artists without like buttons

ytmusicapi/mixins/browsing.py, ytmusicapi/parsers.py
Some artists, for example https://music.youtube.com/channel/UCl69tOzr3a_ZjKB6SuCivVA doesn't have subscriber count. It raises following exception
```
Traceback (most recent call last):
File "/var/www/music/ytmusicapi/ytmusic.py", line 14, in <module>
result = ytmusic.get_artist(sys.argv[2])
File "/usr/local/lib/python3.6/dist-packages/ytmusicapi/helpers.py", line 62, in _impl
return method(self, *method_args, **method_kwargs)
File "/usr/local/lib/python3.6/dist-packages/ytmusicapi/ytmusic.py", line 318, in get_artist
['subscriberCountText', 'runs', 0, 'text'])
File "/usr/local/lib/python3.6/dist-packages/ytmusicapi/parsers.py", line 330, in nav
root = root[k]
KeyError: 'subscriberCountText'
```
This PR fixes it.
=> Fix KeyError when artist doesn't have subscribers count

ytmusicapi/setup.py
In Chrome DevTools, request header names are shown in lowercase and passing them makes current `YTMusic.setup()` fail with:
```
$ cat testrun.py
import ytmusicapi
ytmusicapi.YTMusic.setup('yt.json')
$ python testrun.py
Please paste the request headers from Firefox and press Ctrl-D to continue:
cookie: VISITOR_INFO1_LIVE=[masked]
Traceback (most recent call last):
File "testrun.py", line 3, in <module>
ytmusicapi.YTMusic.setup('yt.json')
File "/home/sarisia/repo/github.com/sigma67/ytmusicapi/ytmusicapi/ytmusic.py", line 129, in setup
return setup(filepath, headers_raw)
File "/home/sarisia/repo/github.com/sigma67/ytmusicapi/ytmusicapi/setup.py", line 37, in setup
raise Exception(
Exception: The following entries are missing in your headers: Cookie. Please try a different request (such as …
```
=> Case-insensitive header parsing in setup()

ytmusicapi/mixins/library.py, ytmusicapi/parsers/library.py, ytmusicapi/parsers/utils.py
This is my attempt to fix #52.
When YTMusic sends incomplete response with less then per_page (25 songs), then request is retried till valid response or till max_retries number is reached.  Usually after single retry, the response is valid. I know it's not the perfect solution,  it costs performance to retry these request and complicates code a bit, but I think that more accurate results are better than fast ones. 
`resend_request_until_parsed_response_is_valid()` is generic method and can be used to validate any request. Currently I fixed only `get_library_songs call`. Let me know, what you think about it. If you approve the solution, I will prepare another fix for `get_playlist`.
=> Fix for incomplete get_library_songs request

.gitignore, tests/test.py, ytmusicapi/mixins/uploads.py
fixes #71 
Used the same error checking logic as in get_library_upload_albums().
I wanted some unit tests so I created tests that verify an empty list is returned for these functions, But of course they assume that your upload library is empty, so I set them to be skipped. I can delete them if you think they're unnecessary, but I wanted to show that I used them to verify my code.
Updated the .gitignore with a couple standard python ignores that were showing as diffs for me.
=> Return empty list if no songs are uploaded

ytmusicapi/mixins/browsing.py
Simple addition of indentation so the `if` statement is evaluated only if the previous one is true. Found with video_id `gzo0xPx26hs`.
=> Logic fix in BrowsingMixin().search()

ytmusicapi/mixins/browsing.py
The example in the documentation for `get_streaming_data()` was not properly indented.
=> Fix documentation for `get_streaming_data()`

ytmusicapi/parsers/library.py
I got following exception, when I trying to get singles list, when some singles have no year [(this artist, for example)](https://music.youtube.com/browse/UClLLt3Gfr07OVs3qgWrOWjQ)
```
Error Output:
================
Traceback (most recent call last):  
File \"/var/www/music/python/ytmusic.py\", line 21, in <module>
result['singles']['results'] = ytmusic.get_artist_albums(result['singles']['browseId'], result['singles']['params'])
File \"/var/www/music/python/ytmusicapi/ytmusicapi/mixins/browsing.py\", line 334, in get_artist_albums
albums = parse_albums(results)  
File \"/var/www/music/python/ytmusicapi/ytmusicapi/parsers/library.py\", line 51, in parse_albums
run_count = len(data['subtitle']['runs'])
KeyError: 'runs'
```
This PR fixes it.
Nice to see this project alive and being actively …
=> Fix KeyError: 'runs' if album has no year

ytmusicapi/parsers/browsing.py
They were passed backwards, so even for playlists which contain the
info, it was not being captured.
=> Flip re.search parameters when parsing playlist info.

ytmusicapi/mixins/uploads.py
I found when uploading songs it was uploading to the wrong account, this fixes that behavior to respect what is defined in the headers
=> Respect the authuser defined in headers_json when uploading a song

ytmusicapi/parsers/__init__.py, ytmusicapi/parsers/browsing.py
This PR gets the `musicVideoType` param from video responses. It apparently has two possible values: `MUSIC_VIDEO_TYPE_UGC` or `MUSIC_VIDEO_TYPE_OMV`, which I guess that stands for user generated content and official music video.
When the music video is uploaded by the owner of the track, it has the value `MUSIC_VIDEO_TYPE_OMV`.
=> get videoType from video results

ytmusicapi/mixins/browsing.py
The current check is meant to detect channels with only video content,
but it also hits small bands that for example have only released singles
so far. An example for this is "UC1uK8RT3m4nNpXmOSsFsZeg".
Since failing is not really helpful anyway (for example audiotub could still play only the sound of a channel that contains only videos),
I propose to remove the check altogether.
=> get_artist: Don't fail on channels with only one category of content

ytmusicapi/helpers.py
Due to the SimpleCookie issue described [here](https://github.com/sigma67/ytmusicapi/issues/294), cookies are not properly parse when they include quotes. As the "YT_CL" cookie includes quotes, this breaks the cookie parser and throws the following exception:
```
Exception: Your cookie is missing the required value __Secure-3PAPISID
```
While one solution is to [completely re-write the cookie parser](https://github.com/django/django/commit/93a135d111c2569d88d65a3f4ad9e6d9ad291452) to fix this issue, a much simpler one may be to just remove quotes from cookies altogether. Authentication succeeds after removing the quotes from the cookies.
=> Remove quotes from cookies

ytmusicapi/mixins/playlists.py, ytmusicapi/parsers/playlists.py
Based on https://github.com/sigma67/ytmusicapi/pull/264 and https://github.com/sigma67/ytmusicapi/pull/265
This PR adds the `videoType` field on playlist items.
=> return videoType on playlist items

ytmusicapi/auth/browser.py, ytmusicapi/auth/headers.py, ytmusicapi/auth/oauth.py
Hi 👋 ,
I use this project as a dependency for a project where I retrieve an OAuth token myself and set it on the headers to authenticate. Since version 1.0.1 this started failing, because this method is not recognized as either browser_auth or oauth. 
This PR extends the browser check to make sure that the `Authorization` value is an OAuth token in case no `Cookie` is supplied.
Regards,
Marvin
=> Add external OAuth case to browser check

ytmusicapi/mixins/playlists.py
This PR fixes parsing of playlists that do not have a `['secondSubtitle']['runs']` property. An example of this play list is https://music.youtube.com/playlist?list=RDATgXd-
=> Fix 'secondSubtitle' KeyError for some playlists

ytmusicapi/parsers/playlists.py
The count in parse_playlist_items is not referenced elsewhere in the function.
=> Small edit only - removed redundant loop counter

ytmusicapi/mixins/uploads.py
Easy quick change. Just moving the pop_songs_random_mix() call to be after the check for empty results.
=> Move pop_songs_random_mix to be after results check.

README.rst
Updated the hyperlink to "tests" in README.rst
=> Hyperlink to "tests" doesn't actually link to tests in README

tests/conftest.py, tests/mixins/test_browsing.py, ytmusicapi/parsers/playlists.py
Simple fix for #515 and adds test case for albums with unavailable tracks. 
Issue could alternatively be solved by extending nav's none_if_absent to coerce nullish return values. thoughts?
=> get_album: track_number returns none when track unavailable + test

ytmusicapi/parsers/search.py
Issue - https://github.com/sigma67/ytmusicapi/issues/518
These offsets cause an issue 
Fix, I test this way 
Before
[BeforeChange.txt](https://github.com/sigma67/ytmusicapi/files/13929569/BeforeChange.txt)
After
[AfterChanges.txt](https://github.com/sigma67/ytmusicapi/files/13929572/AfterChanges.txt)
Differences
Only issue is this 
But this is because code forced in to append `None` for artist without `Id` but then again, what if an artist name is "Album" can't just filter that out by keyword. I think this append of `None` should be taken out because with the way youtube music and youtube topic channels are auto-created I think it is safe to say most artists would have an id, no? 
Let me know and I can commit that change, thanks!
=> Remove offset + fix top result

ytmusicapi/ytmusic.py
This PR adds the missing `AuthType.OAUTH_CUSTOM_FULL` mode when calculating the headers. We (Music Assistant) use our own web-based OAuth process to retrieve an acces token. In this scenario we also provide the other required headers to interact with Youtube Music.
=> Fix OAUTH_CUSTOM_FULL mode

tests/mixins/test_search.py, ytmusicapi/parsers/search.py
parse playlists appearing in top results returning results the same way as for other playlists found be search()
=> handle playlists appearing in top results (closes #524)

ytmusicapi/navigation.py
There's a user reporting a KeyError in nav(), so I've changed it to print out the key and dict for future debugging.  Also, a bare Exception was used to capture a dictionary failure, removed that since my change checks for the existence of the key in the dictionary. If this is objectionable at all, you probably should change it to catching a KeyError rather than catching Exception.
This is to gather information for #539
=> nav() now displays some debugging information on KeyError

ytmusicapi/mixins/library.py, ytmusicapi/mixins/playlists.py, ytmusicapi/mixins/uploads.py
Adding Optional typing for limit in methods whose documentation explicitly allows the use of None type for no limit. This fixes wrong error hinting in editors.
[ contribution requested in #565 ]
=> adding Optional type hinting for limits ( fix #565 )

ytmusicapi/mixins/library.py
`get_account_info()` raises a KeyError if the user does not have a channel handle because they never created a YouTube channel. Seems like a perfect reason to use the handy `none_if_absent` flag :)
=> Prevent KeyError when using get_account_info() on a user that doesn't have a YouTube channel

tests/mixins/test_playlists.py, tests/mixins/test_uploads.py, ytmusicapi/parsers/_utils.py, ytmusicapi/parsers/uploads.py
Fixes #578 
This prevents a possible KeyError or a int-parsing error when an uploaded song has a duration that is not a valid value like "3:31".
Per-recent changes by Google, an uploaded song can have a duration of `' '` or simply not have a `fixedColumns` object at all. This is most commonly seen immediately after uploading a song but can be seen in other cases as well.
I added a unit test that exercises this. It uploads a song and then starts calling `get_library_upload_songs()` in a loop, waiting for the song to be available. Without my duration fix, this encounters a parsing error. With the fix, it succeeds.
=> Gracefully retrieve uploaded songs with a blank duration (#578)

ytmusicapi/mixins/search.py, ytmusicapi/parsers/search.py
Contributes to sigma67/ytmusicapi#585
`playlistId` is available in the search response and can be used to add an album to the library via `like/like` endpoint. So, including the `playlistId` when the query is filtered by `albums`  could be helpful.
=> parse_seach_result: add playlist id to album search

ytmusicapi/parsers/search.py
A search result of ```"resultType": "playlist"``` from YTMusic.search() contains a field ```"itemCount"```, which was always serialized as a json string, despite representing a number.
This pull request casts the python str to int, so ```"itemCount"``` is serialized as a json number.
=> playlist search result "itemCount" field cast to int

.github/workflows/coverage-pr.yml, .github/workflows/coverage.yml, tests/mixins/test_playlists.py, ytmusicapi/mixins/playlists.py
Patch to allow `edit_playlist()` to move a title to the end of a playlist. See #601.
=> edit_playlist(): Allow moving title to bottom of playlist

ytmusicapi/parsers/podcasts.py
This is a proposed fix for issue https://github.com/sigma67/ytmusicapi/issues/613, where if an album artist is "Various Artists" then there is no associated artist ID.
closes #613
=> Return blank album author ID when it doesn't exist.

ytmusicapi/parsers/playlists.py
Fixed invalid artists info for get_album from https://github.com/sigma67/ytmusicapi/issues/617 issue.
Bug was a result of my changes in #612.
This is a flexColumn for an artist:
```javascript
{
"musicResponsiveListItemFlexColumnRenderer": {
"text": {},
"displayPriority": "MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH"
}
}
```
it was skipped in parsing, because it did not have `navigationEndpoint` and `text` was empty. "Plays" column has been used as an artist instead. I removed empty `text` check. Now it will be used as unrecognized artist column. Then `parse_song_artists` method will return `None` and in the end in  `get_album` method if artist track is `None`, then primary album artist will be used. So it will work exactly as in 1.7.3 and before.
Closes #617.
=> get_album: fix invalid track list artists (#617)

tests/mixins/test_playlists.py, ytmusicapi/mixins/playlists.py, ytmusicapi/parsers/playlists.py
Use RegEx search to search for track count integer instead of using indexing. If the number cannot be extracted, return 0 as a fallback. I never hit the error in parsers, but seeing as the logic is the same, I went ahead and changed it there too.
Addresses https://github.com/sigma67/ytmusicapi/issues/608
=> Extract song count from text

ytmusicapi/parsers/playlists.py
Quick fix for get_playlist method. Some playlist items had None as a title. (#622)
After refactor in (#612),  title is resolved using `watchEndpoint`. Podcast episodes do not have one. They have `browseEndpoint` with `pageType = MUSIC_PAGE_TYPE_NON_MUSIC_AUDIO_TRACK_PAGE` instead.
=> get_playlist: fix title for podcast episodes (#622)

docs/source/reference.rst, tests/mixins/test_browsing.py, ytmusicapi/mixins/browsing.py
=> add get_user_videos

ytmusicapi/parsers/search.py
=> search: fix playlistId on album results

ytmusicapi/mixins/playlists.py
While I was reading the docs to append video items, I got confused by the setVideoId parameter. I added the missing field to the get_playlists_id example and copied the definition to the edit playlist documentation.
I hope this is ok, it's a very small change, but I think it might help others. I really appreciate the time you take by looking at this.
=> Very small additions to documentation

tests/mixins/test_playlists.py, tests/mixins/test_podcasts.py, tests/mixins/test_search.py, ytmusicapi/mixins/playlists.py
=> fix(playlists): handle missing regex group in trackCount

tests/mixins/test_browsing.py, tests/mixins/test_uploads.py, ytmusicapi/mixins/uploads.py
=> upload_song: add error when file exceeds limit of 300MB 

tests/conftest.py, tests/mixins/test_playlists.py, ytmusicapi/mixins/playlists.py, ytmusicapi/parsers/playlists.py
Sometimes the object 'runs' is not to be found within title, but within
subtitle. This PR makes ytmusicapi look in both places.
Closes #656
=> fix #656: attempt to find runs in subtitle if not in title

tests/mixins/test_playlists.py, ytmusicapi/parsers/_utils.py
=> Fix duration parsing for very long videos

tests/auth/test_oauth.py, tests/mixins/test_library.py, tests/mixins/test_playlists.py, ytmusicapi/mixins/library.py, ytmusicapi/parsers/playlists.py
=> Fix get_history

ytmusicapi/setup.py
If no `--file` argument is provided to setup, `as_uri()` throws a ValueError when it tries to get the relative path to print to the console. Using `resolve()` will work in both case (`--file` provided or not provided).
Fixes #699
=> fix(setup): Use resolve() before invoking as_uri()

tests/mixins/test_playlists.py, ytmusicapi/continuations.py, ytmusicapi/mixins/playlists.py, ytmusicapi/parsers/playlists.py
=> fix get_playlist continuations

ytmusicapi/ytmusic.py
```diff
import ytmusicapi
import timeit
yt = ytmusicapi.YTMusic()
for _ in range(2):
print(round(timeit.timeit(lambda: yt.get_album('MPREb_4pL8gzRtw1p'), number=1) * 1000))
-710
-593
+753
+146
```
=> cache visitor ID on first use

ytmusicapi/parsers/browsing.py
=> fix #751: `parse_video` returns always a video ID or `None`

docs/source/setup/oauth.rst
Update documentation to add a missing parenthesis.
=> typo: missing parentheses in oauth.rst

ytmusicapi/parsers/browsing.py
As seen in #805 , there was a case where a user had a "zombie" playlist stuck in their library with no title, tracks, or artwork, and `parse_playlist` was throwing a `KeyError` because of the missing title, causing `get_library_playlists` to throw an error.
This fix just sets `none_if_absent=True` for the "title" attribute. I am hesitant to go a step further and make similar accomodations for other fields that might be missing, since the only field that I know for sure was missing from the response was "title". In my opinion I would rather wait for an occurence where it throws a KeyError on another field than start putting `none_if_absent` on everything. It's possible there was still a "thumbnails" attribute in the JSON even though the playlist didn't have a thumbnail.
=> Don't throw an error if playlist title is missing (fixes #805)
